depotlifecycle:
  client:
    url: "${LIFECYCLE_ENDPOINT:`http://localhost:8086/`}"
    authorization: "${LIFECYCLE_AUTHORIZATION:`Basic bm92YWxpZGF0ZTpub3ZhbGlkYXRl`}" # no validate defaults
micronaut:
  application:
    name: depotlifecycle
  server:
      port: 8086
  endpoints:
    health:
      enabled: true
      details-visible: ANONYMOUS
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    enabled: true
    authentication: bearer
    intercept-url-map:
      - pattern: /swagger/**
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /redoc/**
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /rapidoc/**
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /swagger-ui/**
        httpMethod: GET
        access:
          - isAnonymous()
    endpoints:
      login:
        enabled: true
        path: /api/login
      oauth:
        enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: pleaseChangeThisSecretForANewOne
jackson:
  trim-strings: true
  bean-introspection-module: true
  always-serialize-errors-as-list: false
  serialization:
    indentOutput: true
    writeDatesAsTimestamps: false
    writeDatesWithZoneId: false
  deserialization:
#    useBigIntegerForInts: true
#    failOnUnknownProperties: false
datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
jpa:
  default:
    entity-scan:
      packages: 'depotlifecycle.domain'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: false
