depotlifecycle:
  client:
    url: "${LIFECYCLE_ENDPOINT:`http://localhost:8086/`}"
    authorization: "${LIFECYCLE_AUTHORIZATION:`Basic bm92YWxpZGF0ZTpub3ZhbGlkYXRl`}" # no validate defaults
  documentation:
    application:
      description: |
        # Purpose

         A depot centric API for managing the interchange activity & repair lifecycle of a shipping container.  The API is expected to be used by Customers, Depots, and Owners to facilitate real time communication between systems instead of traditional EDI files.


         # Overview

         The depot lifecycle API is a RESTful API.  It's requests & responses are loosely based upon traditional EDI files.  For code definitions, explanations, or traditional EDI definitions refer to [IICL TB 002, February 2003](https://www.iicl.org/iiclforms/assets/File/public/bulletins/TB002_EDIS_February_2003.pdf).


         # JSON

         The requests and responses of this API are formatted according to the [JSON](https://www.json.org/) standard.

         ## Null vs Absent

         For all types other than arrays, nullable and absent are equivalent by this specification.  For example, if a non-array attribute is marked optional it may be excluded from the JSON or it may be explicitly set to null.  However, to keep request sizes small, it is recommended to prefer excluding attributes rather than sending an explicit null.

         For arrays, null should be avoided.  For example, if the array is empty or there are no values expected for the array then either the field can be excluded from the JSON or an empty array should be transmitted.

         ## Blank Values

         Blank values should generally be avoided. Send a `null` value instead of blank. The API documentation represents blank as not allowed by setting the minimum length to 1 and allowing the field to be null. 
         ## Default Values

         Anywhere a default value is defined in this API, if null is transmitted, it is assumed the default value will be used.

         ## Forward Compatibility

         To maintain compatibility with future versions of this specification, it is recommended to never fail on unknown properties in requests or responses.


         # Reference

         This API is documented by the [OpenAPI](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md) specification.  This page was initially created by the [Swagger-Editor](https://github.com/swagger-api/swagger-editor) tool and later autogenerated via the [sample java application](https://github.com/IICL-API/depot-lifecycle-api/tree/main/samples/java) in the GitHub repository.  The *yaml* specification file can be found [here](depot-lifecycle-openapi.yaml).


         # Implementation Expectations

         Not all parties are required or expected to implement every feature. Any feature not implemented should return a http status code of `501`.


         # APIs to Implement

         While anyone is free to implement all or a selected set of the APIs listed here, the typical use case would be for Depot to Lessor communication.  For the Depot, they would call the Lessor's system using the following APIs:

         1. POST - create a gate record 

         2. PUT - update a gate record 

         3. POST - create an estimate revision 

         4. PUT - marks a shipping container repaired 

         These APIs allow the Depot to report the initial gate in movement, issue gate data corrections (i.e. the damage status or activity date), participate in the estimate process (i.e. creation, surveys, and customer approval), notify when a shipping container is repaired, and create a gate out for leaving the depot.


         # Depot Identifiers

         Depot or facility identifiers, henceforth referred to as `EDI Address`, `CompanyId`, or `Party Id` in this document, are maintained by The Bureau International des Containers (BIC) and officially known as the BIC Facility Code. For codes and more information please refer to [https://www.bic-code.org/bic-facility-codes](https://www.bic-code.org/bic-facility-codes/).


         # Deprecation

         If this API version were to be discontinued, a minimum of 6 months time would pass before it's removal.


         # Change Log Types

         * api - a backend api change that will require development to support
         * doc - a documentation only change, no implementation impact
         * server - a change (or implementation) to the example server implementation
         * client - a change (or implementation) to the example client implementation


         # Change Log

         * 2.2.1
            - (api) Estimate Photo support for line items and the overall estimate (header).

         * 2.2.2
            - (api) Estimate Line Items are optional.
            - (api) Error Responses optionally support multiple messages via a details field.
            - (api) Various improvements for BETA APIs.

         * 2.2.3
            - (api) Party model (optional):
                - Latitude & Longitude
                - Physical Address
                - Contact Phone, Fax, & Phone Number fields
            - (api) Insurance Coverage model:
                 - Add indicator for insurance coverage applicable to CTL scenarios
            - (api) Release & Redelivery models - Status field
            - (api) Redelivery model - Add field to store estimate recipient emails
            - (api) RedeliveryUnit model - Add cargo # to identify type of cargo by UN or other standard numbers
            - (api) RedeliveryUnit model - Add technical bulletins field
            - (api) Release search - Add search flag to find candidate units

         * 2.2.4
            - (api) Added separate section for shared models to documentation (show the request based version where possible to avoid confusion).
            - (doc) Documented suggested security schemes for easier adoption with API importing tools.
            - (doc) Clarified best practices for JSON produced or consumed by this API.
                - Clarified Default Value handling.
                - Clarified Null vs Absent Value handling.
                - Documented forward compatability best practices.
            - (doc) Fixed type definitions for query parameters - `string` will now show instead of `object`.
            - (doc) Fixed type definitions for path parameters - `string` will now show instead of `object`.
            - (doc) Fixed minimum length documentation for damage location code on Estimate Line Item.
            - (api) Add `type` to Gate Status API.
            - (api) Change `currentInspectionCriteria` on Gate Status & Create APIs to optional since Estimates are not always required.
            - (api) Add `gateCheck` option to Redelivery & Release search APIs, defaulted so previous query behavior is the same.
            - (doc) Clarify that the reefer set point temperature is in Celsius on the ReleaseDetail model.
            - (doc) Clarify `inspectionCriteria` field on `RedeliveryUnit` is meant to convey the estimation instructions.
            - (doc) Fix array string examples.
            - (api) Estimate Photo Upload Proposal:
                - For all photo APIs, assume a default status of `BEFORE` so that it is not required.
                - Estimate Photo Upload endpoint
                - Added identifier field, `relatedId`, to `EstimateAllocation` to use to upload photos
                - Added identifier field, `relatedId`, to `WorkOrder` to use to upload photos
            - (api) Gate Photo Upload Proposal:
                - Gate Photo Upload endpoint
                - Added identifier field, `relatedId`, to `GateResponse` to use to upload photos

         * 2.2.5
            - (api) Share the same Gate Photo model between Create & Update since they are the same.

         * 2.2.6
            - (client, server) No intentional API changes.  Added Estimate & Gate clients for easier testing.

         * 2.2.7
            - (api) Add optional `tax` field to Estimate Line Item; typically used for total verification & for system implementations that do not store the tax rate of the depot.
            - (api) Add optional `taxRates` field to Estimate; typically used for system implementations that do not store the tax rate of the depot.
            - (api) Add optional `desiredHumidity` field to the ReleaseDetail model.
            - (api) Move binary estimate & gate photo upload apis from alpha to beta.
            - (client) Minor fetch fixes to support estimate & gate searches.
            - (api) Change Customer & Recipient party references on Release/Redelivery to an external party - a party that supports either the `companyId` or `code` for identification.

         * 2.2.8
            - (api, client, server) Add InsuranceCoverageItem to indicate specific repair combinations that are or are not covered under insurance.
            - (api, client, server) Add `targetGrade` to RedeliveryUnit to indicate the expected grade of the container upon arrival in a depot.
            - (api, client, server) Add `licensePlate` to Party and ExternalParty.
            - (api, client, server) Add `trucker` as an external party to GateCreateRequest.
            - (api, client, server) Add `trucker` as an external party to GateUpdateRequest.
            - (doc) Reorder field definitions on EstimateLineItem to reflect entry order.  Should only affect documentation since json order does not matter.
            - (api, client, server) Add EquipmentDetail model to store various information about the shipping container.
            - (api, client, server) Add ChassisInfo model for EquipmentDetail to store information specific to chassis.
            - (api, client, server) Add InspectionReport model for EquipmentDetail to capture inspection results.
            - (api, client, server) Add TireTreadMeasurement model for EquipmentDetail to capture tire tread measurements for chassis.
            - (api, client, server) Add optional `equipmentDetail` to GateCreateRequest model to submit optional data between depots and shipping lines.
            - (api, client, server) Add optional `equipmentDetail` to GateUpdateRequest model to submit optional data between depots and shipping lines.
            - (client) Switch to built in date and datetime-local controls for easier data entry.
            - (api, client, server) Add GensetInfo model for EquipmentDetail to store various information specific to gensets.
            - (client, server) Packaging cleanup for example implementation.
            - (api, client, server) While fields can be null, they should generally not be blank.
            - (api) Add `gensetInfo` to RedeliveryUnit model.
            - (api) Add `chassisInfo` to RedeliveryUnit model.
            - (api, client, server) Add `loaded` to EquipmentDetail model.
            - (api, client, server) Add `cargoSeals` to EquipmentDetail model.
            - (doc) Clarify `adviceNumber` on GateCreateRequest.
            - (api, client, server) `loaded` should support `null` for unknown states on the EquipmentDetail model.
            - (api, server) Add `insuranceCoverage` to EstimateAllocation model.


         # Security & Authentication

         To ensure secure communication, all endpoints of this API should use the https protocol instead of http.  Authentication methods will differ between systems, but two popular methods are JSON Web Tokens and Static Tokens.  Examples for both of these follow.


        ## JSON Web Token

         [JSON Web Token, or JWT](https://jwt.io/), is used for stateless authentication.  Since all requests are sent using https, tokens are not encrypted.  Tokens follow the [RFC 6750 Bearer Token](https://tools.ietf.org/html/rfc6750) format.


        ### 1. Example JWT Token


         ```
         {
        	"username": "jdoe",
        	"roles": [
        		"ROLE_GATE_CREATE",
        		"ROLE_GATE_UPDATE"
        	],
        	"email":"j.doe@example.com",
        	"token_type":"Bearer",
        	"access_token":"eyJhbGciOiJIUzI1NiJ9...",
        	"expires_in":3600,        
        	"refresh_token":"eyJhbGciOiJIUzI1NiJ9..."
         }
         ```

         An access_token is provided for authentication to API endpoints and a refresh_token is provided to generate a new access_token when one expires.


         ### 2. Obtaining an access token

         Issuing a POST request to `/api/login` with a username and password payload will cause a JWT token to be issued in the response.


         ```
         POST /api/login HTTP/1.1
         Content-Type: text/plain; charset=utf-8
         Host: www.example.com


         {
        	"username": "jdoe",
        	"password": "jdoepassword"
         }
         ```

         ### 3. Refreshing an expired token

         Tokens created by invoking the login endpoint expire after a determined period.  Issuing a POST request to `/oauth/access_token` with: the refresh_token from the JWT token previously issued and a grant_type of refresh_token will reissue a new JWT token.

         ```
         POST /oauth/access_token HTTP/1.1
         Host: www.example.com
         Content-Type: application/x-www-form-urlencoded
         grant_type=refresh_token&refresh_token=eyJhbGciOiJIUzI1NiJ9...
         ```


         ### 4. Checking if a token is valid

         Any token can be checked if it's still valid by issuing a POST request to `/api/validate`.

         ```
         GET /api/validate HTTP/1.1
         Host: www.example.com
         Authorization: Bearer eyJhbGciOiJIUzI1NiJ9...
         Content-Type: application/json; charset=utf-8
         ```


         ### 5. Accessing a protected resource

         Use the 'Authorization' header to supply the JWT for authentication to a protected resource.

         ```
         GET /api/v2/gate/CONU1234561 HTTP/1.1
         Host: www.example.com
         Authorization: Bearer eyJhbGciOiJIUzI1NiJ9...
         ```


        ## Static Tokens

         A static token is assigned by an external process or system.  After assignment, any documented API endpoint can be invoked by including a header of "Authorizaton" and the value of the token.  Some systems will assign static tokens that are JWTs, in that case "Bearer " should prefix the token in the header value.


        ### Static (JWT) Token Example

         Assuming an assigned JWT of "eyJhbGciOiJIUzI1NiJ9", an API gate show request would look like: 

        ```
         GET /api/v2/gate/CONU1234561 HTTP/1.1
         Host: www.example.com
         Authorization: Bearer eyJhbGciOiJIUzI1NiJ9
         ```
micronaut:
  application:
    name: depotlifecycle
  server:
      port: 8086
  endpoints:
    health:
      enabled: true
      details-visible: ANONYMOUS
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    enabled: true
    authentication: bearer
    intercept-url-map:
      - pattern: /swagger/**
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /redoc/**
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /rapidoc/**
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /swagger-ui/**
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /client/**
        access:
          - isAnonymous()
    endpoints:
      login:
        enabled: true
        path: /api/login
      oauth:
        enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: pleaseChangeThisSecretForANewOne
jackson:
  trim-strings: true
  bean-introspection-module: true
  always-serialize-errors-as-list: false
  serialization:
    indentOutput: true
    writeDatesAsTimestamps: false
    writeDatesWithZoneId: false
  deserialization:
    READ_UNKNOWN_ENUM_VALUES_AS_NULL: true
#    useBigIntegerForInts: true
#    failOnUnknownProperties: false
datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
jpa:
  default:
    entity-scan:
      packages: 'depotlifecycle.domain'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: false