pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }

    includeBuild("build-logic")
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }
}

rootProject.name="depotlifecycle"

enableFeaturePreview('GROOVY_COMPILATION_AVOIDANCE')