plugins {
    id 'groovy-gradle-plugin'
}

repositories {
    gradlePluginPortal()
    mavenCentral()
}

dependencies {
    implementation 'com.gradleup.shadow:shadow-gradle-plugin:9.5.1'
    implementation 'io.micronaut.application:io.micronaut.application.gradle.plugin:5.0.2'
    implementation 'io.micronaut.aot:io.micronaut.aot.gradle.plugin:5.0.2'
    implementation 'io.micronaut.docker:io.micronaut.docker.gradle.plugin:5.0.2'
    implementation 'io.micronaut.openapi:io.micronaut.openapi.gradle.plugin:5.0.2'
    implementation 'name.remal.lombok:name.remal.lombok.gradle.plugin:3.2.0'
}
